name: Release

on:
  push:
    branches:
      - trunk

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          npm i -g semantic-release
          npm i -g @semantic-release/changelog
          npm i -g conventional-changelog-conventionalcommits
          npm i -g @semantic-release/git
          npm i -g @semantic-release/github
          npm i -g @semantic-release/commit-analyzer
          npm i -g @semantic-release/release-notes-generator          

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        run: semantic-release --debug
